# Generated by Django 5.1.3 on 2024-11-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='secaoensino',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='ensino/'),
        ),
    ]
