# Generated by Django 5.1.3 on 2024-11-12 18:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_secaoensino_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='unidade',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='texto_principal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='texto_secundario',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='secaoensino',
            name='descricao',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='secaoensino',
            name='imagem',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='secoes/'),
        ),
        migrations.AlterField(
            model_name='secaoensino',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
