# Generated by Django 5.1.3 on 2024-11-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_agendamento_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='unidade',
            field=models.CharField(choices=[('Primavera', 'Unidade Primavera'), ('BelaVista', 'Unidade BelaVista')], default='Primavera', max_length=20),
        ),
    ]
